package pt.isec.prompt;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import pt.isec.ai.CommonLLM;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Optional;

public class InstanceBuilder implements SimpleJsonDeserializer {
    public <T> Optional<T> getInstance(String prompt, CommonLLM llm, Class<T> type, int attempts) throws RuntimeException {
        while (attempts > 0) {
            String response = llm.request(prompt);

            Optional<T> instance = fromJson(response, type);

            if (instance.isPresent()) {
                return instance;
            }

            attempts--;
        }
        return Optional.empty();
    }

    @Override
    public <T> Optional<T> fromJson(String json, Class<T> type) {
        Gson gson = new GsonBuilder()
                .registerTypeAdapter(Duration.class, new DurationAdapter())
                .registerTypeAdapter(LocalDateTime.class, new LocalDateTimeAdapter())
                .create();

        try {
            T instance = gson.fromJson(json, type);
            return Optional.of(instance);
        } catch (Exception e) {
            return Optional.empty();
        }
    }
    public String getSampleMealPlanJSON() {
        return "{" +
                "\"goal\":\"Weight Loss\"," +
                "\"begin\":\"2024-11-25T00:00\"," +
                "\"end\":\"2024-12-01T00:00\"," +
                "\"meals\":[" +
                // Day 1
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-25T08:00\",\"recipe\":{\"name\":\"Grilled Lemon Herb Chicken\",\"description\":\"A flavorful and juicy grilled chicken marinated in lemon and herbs.\",\"servings\":1,\"prep\":105,\"reminders\":[{\"data\":\"Preheat the grill to medium-high heat.\"},{\"data\":\"Marinate chicken for at least 30 minutes.\"}],\"ingredients\":[{\"name\":\"Chicken Breast\",\"description\":\"Lean protein source, skinless and boneless.\",\"quantity\":400,\"units\":\"grams\",\"calories\":660,\"macros\":{\"proteins\":124.0,\"carbs\":0.0,\"fats\":14.0},\"allergens\":[]},{\"name\":\"Olive Oil\",\"description\":\"Healthy fat used for marinating and cooking.\",\"quantity\":30,\"units\":\"milliliters\",\"calories\":240,\"macros\":{\"proteins\":0.0,\"carbs\":0.0,\"fats\":27.0},\"allergens\":[]},{\"name\":\"Lemon Juice\",\"description\":\"Freshly squeezed juice for flavor.\",\"quantity\":50,\"units\":\"milliliters\",\"calories\":15,\"macros\":{\"proteins\":0.0,\"carbs\":5.0,\"fats\":0.0},\"allergens\":[]},{\"name\":\"Garlic\",\"description\":\"Adds a strong flavor to the marinade.\",\"quantity\":10,\"units\":\"grams\",\"calories\":15,\"macros\":{\"proteins\":0.6,\"carbs\":3.5,\"fats\":0.1},\"allergens\":[]},{\"name\":\"Dried Oregano\",\"description\":\"Herb used for seasoning.\",\"quantity\":5,\"units\":\"grams\",\"calories\":15,\"macros\":{\"proteins\":0.8,\"carbs\":3.2,\"fats\":0.3},\"allergens\":[]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-25T12:30\",\"recipe\":{\"name\":\"Caesar Salad\",\"description\":\"A classic Caesar salad with grilled chicken and fresh romaine lettuce.\",\"servings\":2,\"prep\":20,\"reminders\":[{\"data\":\"Prepare dressing before assembling the salad.\"}],\"ingredients\":[{\"name\":\"Romaine Lettuce\",\"description\":\"Fresh and crisp base for the salad.\",\"quantity\":200,\"units\":\"grams\",\"calories\":34,\"macros\":{\"proteins\":2.9,\"carbs\":7.3,\"fats\":0.4},\"allergens\":[]},{\"name\":\"Grilled Chicken\",\"description\":\"Sliced, seasoned chicken breast.\",\"quantity\":150,\"units\":\"grams\",\"calories\":248,\"macros\":{\"proteins\":46.0,\"carbs\":0.0,\"fats\":6.2},\"allergens\":[]},{\"name\":\"Caesar Dressing\",\"description\":\"Rich and creamy dressing.\",\"quantity\":50,\"units\":\"milliliters\",\"calories\":200,\"macros\":{\"proteins\":1.5,\"carbs\":3.0,\"fats\":20.0},\"allergens\":[\"Egg\"]},{\"name\":\"Parmesan Cheese\",\"description\":\"Adds a nutty and salty flavor.\",\"quantity\":20,\"units\":\"grams\",\"calories\":86,\"macros\":{\"proteins\":7.3,\"carbs\":0.8,\"fats\":6.2},\"allergens\":[\"Dairy\"]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-25T19:00\",\"recipe\":{\"name\":\"Spaghetti Bolognese\",\"description\":\"Classic Italian pasta with rich meat sauce.\",\"servings\":4,\"prep\":60,\"reminders\":[{\"data\":\"Simmer sauce for at least 30 minutes for better flavor.\"}],\"ingredients\":[{\"name\":\"Ground Beef\",\"description\":\"Protein-packed and savory meat base.\",\"quantity\":500,\"units\":\"grams\",\"calories\":1170,\"macros\":{\"proteins\":70.0,\"carbs\":0.0,\"fats\":95.0},\"allergens\":[]},{\"name\":\"Spaghetti\",\"description\":\"Classic Italian pasta.\",\"quantity\":400,\"units\":\"grams\",\"calories\":1580,\"macros\":{\"proteins\":56.0,\"carbs\":316.0,\"fats\":8.0},\"allergens\":[\"Gluten\"]},{\"name\":\"Tomato Sauce\",\"description\":\"Rich and tangy sauce base.\",\"quantity\":300,\"units\":\"grams\",\"calories\":75,\"macros\":{\"proteins\":2.1,\"carbs\":16.2,\"fats\":0.3},\"allergens\":[]}]}}," +
                // Day 2
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-26T08:00\",\"recipe\":{\"name\":\"Scrambled Eggs with Avocado\",\"description\":\"Fluffy scrambled eggs with creamy avocado slices.\",\"servings\":1,\"prep\":10,\"reminders\":[{\"data\":\"Use low heat for soft eggs.\"}],\"ingredients\":[{\"name\":\"Eggs\",\"description\":\"Rich protein source.\",\"quantity\":3,\"units\":\"units\",\"calories\":210,\"macros\":{\"proteins\":18.0,\"carbs\":1.0,\"fats\":15.0},\"allergens\":[\"Egg\"]},{\"name\":\"Avocado\",\"description\":\"Creamy and healthy fat.\",\"quantity\":100,\"units\":\"grams\",\"calories\":160,\"macros\":{\"proteins\":2.0,\"carbs\":8.0,\"fats\":15.0},\"allergens\":[]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-26T12:30\",\"recipe\":{\"name\":\"Grilled Salmon\",\"description\":\"Grilled salmon fillet served with steamed broccoli.\",\"servings\":1,\"prep\":30,\"reminders\":[{\"data\":\"Season salmon before grilling.\"}],\"ingredients\":[{\"name\":\"Salmon Fillet\",\"description\":\"Rich source of omega-3 and protein.\",\"quantity\":200,\"units\":\"grams\",\"calories\":412,\"macros\":{\"proteins\":40.0,\"carbs\":0.0,\"fats\":28.0},\"allergens\":[\"Fish\"]},{\"name\":\"Broccoli\",\"description\":\"Steamed green vegetable.\",\"quantity\":150,\"units\":\"grams\",\"calories\":52,\"macros\":{\"proteins\":4.0,\"carbs\":10.0,\"fats\":0.6},\"allergens\":[]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-26T19:00\",\"recipe\":{\"name\":\"Vegetable Stir-Fry\",\"description\":\"Colorful stir-fried vegetables with tofu.\",\"servings\":2,\"prep\":25,\"reminders\":[{\"data\":\"Use high heat for quick stir-frying.\"}],\"ingredients\":[{\"name\":\"Tofu\",\"description\":\"Plant-based protein source.\",\"quantity\":250,\"units\":\"grams\",\"calories\":290,\"macros\":{\"proteins\":30.0,\"carbs\":6.0,\"fats\":16.0},\"allergens\":[\"Soy\"]},{\"name\":\"Bell Peppers\",\"description\":\"Crisp and colorful peppers.\",\"quantity\":200,\"units\":\"grams\",\"calories\":50,\"macros\":{\"proteins\":2.0,\"carbs\":12.0,\"fats\":0.2},\"allergens\":[]}]}}," +
                // Day 3
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-27T08:00\",\"recipe\":{\"name\":\"Overnight Oats\",\"description\":\"Creamy oats soaked overnight with fresh fruit.\",\"servings\":1,\"prep\":5,\"reminders\":[{\"data\":\"Prepare the night before and refrigerate.\"}],\"ingredients\":[{\"name\":\"Rolled Oats\",\"description\":\"Base ingredient for overnight oats.\",\"quantity\":50,\"units\":\"grams\",\"calories\":190,\"macros\":{\"proteins\":6.0,\"carbs\":34.0,\"fats\":4.0},\"allergens\":[\"Gluten\"]},{\"name\":\"Milk\",\"description\":\"Dairy or plant-based liquid for soaking oats.\",\"quantity\":200,\"units\":\"milliliters\",\"calories\":100,\"macros\":{\"proteins\":8.0,\"carbs\":12.0,\"fats\":2.0},\"allergens\":[\"Dairy\"]},{\"name\":\"Blueberries\",\"description\":\"Sweet and tangy topping.\",\"quantity\":50,\"units\":\"grams\",\"calories\":29,\"macros\":{\"proteins\":0.4,\"carbs\":7.4,\"fats\":0.2},\"allergens\":[]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-27T12:30\",\"recipe\":{\"name\":\"Chicken Wrap\",\"description\":\"Grilled chicken with fresh veggies in a whole-grain wrap.\",\"servings\":1,\"prep\":15,\"reminders\":[{\"data\":\"Warm the wrap before assembling.\"}],\"ingredients\":[{\"name\":\"Whole-Grain Wrap\",\"description\":\"Fiber-rich base for the wrap.\",\"quantity\":1,\"units\":\"unit\",\"calories\":180,\"macros\":{\"proteins\":7.0,\"carbs\":30.0,\"fats\":4.0},\"allergens\":[\"Gluten\"]},{\"name\":\"Grilled Chicken\",\"description\":\"Lean protein source.\",\"quantity\":150,\"units\":\"grams\",\"calories\":248,\"macros\":{\"proteins\":46.0,\"carbs\":0.0,\"fats\":6.2},\"allergens\":[]},{\"name\":\"Lettuce\",\"description\":\"Crisp and fresh addition.\",\"quantity\":50,\"units\":\"grams\",\"calories\":8,\"macros\":{\"proteins\":0.7,\"carbs\":1.5,\"fats\":0.1},\"allergens\":[]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-27T19:00\",\"recipe\":{\"name\":\"Turkey Meatballs\",\"description\":\"Baked turkey meatballs in marinara sauce.\",\"servings\":4,\"prep\":45,\"reminders\":[{\"data\":\"Preheat oven to 375°F before baking.\"}],\"ingredients\":[{\"name\":\"Ground Turkey\",\"description\":\"Lean and flavorful protein base.\",\"quantity\":500,\"units\":\"grams\",\"calories\":650,\"macros\":{\"proteins\":100.0,\"carbs\":0.0,\"fats\":15.0},\"allergens\":[]},{\"name\":\"Breadcrumbs\",\"description\":\"Adds texture to meatballs.\",\"quantity\":50,\"units\":\"grams\",\"calories\":200,\"macros\":{\"proteins\":4.0,\"carbs\":38.0,\"fats\":2.0},\"allergens\":[\"Gluten\"]},{\"name\":\"Marinara Sauce\",\"description\":\"Tangy tomato sauce.\",\"quantity\":300,\"units\":\"grams\",\"calories\":75,\"macros\":{\"proteins\":2.1,\"carbs\":16.2,\"fats\":0.3},\"allergens\":[]}]}}," +
                // Day 4
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-28T08:00\",\"recipe\":{\"name\":\"Greek Yogurt Bowl\",\"description\":\"Creamy yogurt topped with granola and honey.\",\"servings\":1,\"prep\":5,\"reminders\":[{\"data\":\"Use unsweetened yogurt for fewer calories.\"}],\"ingredients\":[{\"name\":\"Greek Yogurt\",\"description\":\"Protein-rich and creamy base.\",\"quantity\":150,\"units\":\"grams\",\"calories\":100,\"macros\":{\"proteins\":10.0,\"carbs\":5.0,\"fats\":5.0},\"allergens\":[\"Dairy\"]},{\"name\":\"Granola\",\"description\":\"Crunchy topping for texture.\",\"quantity\":30,\"units\":\"grams\",\"calories\":150,\"macros\":{\"proteins\":3.0,\"carbs\":27.0,\"fats\":4.5},\"allergens\":[\"Gluten\",\"Nuts\"]},{\"name\":\"Honey\",\"description\":\"Natural sweetener.\",\"quantity\":15,\"units\":\"grams\",\"calories\":60,\"macros\":{\"proteins\":0.0,\"carbs\":17.0,\"fats\":0.0},\"allergens\":[]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-28T12:30\",\"recipe\":{\"name\":\"Quinoa Salad\",\"description\":\"Nutritious salad with quinoa, black beans, and corn.\",\"servings\":2,\"prep\":20,\"reminders\":[{\"data\":\"Rinse quinoa before cooking.\"}],\"ingredients\":[{\"name\":\"Quinoa\",\"description\":\"Gluten-free whole grain.\",\"quantity\":100,\"units\":\"grams\",\"calories\":120,\"macros\":{\"proteins\":4.0,\"carbs\":21.0,\"fats\":1.9},\"allergens\":[]},{\"name\":\"Black Beans\",\"description\":\"Rich in protein and fiber.\",\"quantity\":100,\"units\":\"grams\",\"calories\":114,\"macros\":{\"proteins\":7.0,\"carbs\":20.0,\"fats\":0.5},\"allergens\":[]},{\"name\":\"Corn\",\"description\":\"Sweet and juicy addition.\",\"quantity\":100,\"units\":\"grams\",\"calories\":86,\"macros\":{\"proteins\":3.2,\"carbs\":19.0,\"fats\":1.2},\"allergens\":[]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-28T19:00\",\"recipe\":{\"name\":\"Beef Stir-Fry\",\"description\":\"Quick and flavorful stir-fry with lean beef and vegetables.\",\"servings\":2,\"prep\":25,\"reminders\":[{\"data\":\"Use a hot wok for even cooking.\"}],\"ingredients\":[{\"name\":\"Beef Strips\",\"description\":\"Lean protein source.\",\"quantity\":300,\"units\":\"grams\",\"calories\":660,\"macros\":{\"proteins\":58.0,\"carbs\":0.0,\"fats\":48.0},\"allergens\":[]},{\"name\":\"Mixed Vegetables\",\"description\":\"Colorful stir-fry blend.\",\"quantity\":200,\"units\":\"grams\",\"calories\":60,\"macros\":{\"proteins\":2.0,\"carbs\":14.0,\"fats\":0.3},\"allergens\":[]}]}}," +
                // Day 5
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-29T08:00\",\"recipe\":{\"name\":\"Protein Pancakes\",\"description\":\"Fluffy pancakes with added protein powder.\",\"servings\":1,\"prep\":15,\"reminders\":[{\"data\":\"Flip pancakes when bubbles form.\"}],\"ingredients\":[{\"name\":\"Protein Powder\",\"description\":\"Boosts protein content.\",\"quantity\":30,\"units\":\"grams\",\"calories\":120,\"macros\":{\"proteins\":25.0,\"carbs\":2.0,\"fats\":1.0},\"allergens\":[]},{\"name\":\"Oats\",\"description\":\"Blended for pancake batter.\",\"quantity\":50,\"units\":\"grams\",\"calories\":190,\"macros\":{\"proteins\":6.0,\"carbs\":34.0,\"fats\":4.0},\"allergens\":[\"Gluten\"]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-29T12:30\",\"recipe\":{\"name\":\"Grilled Tuna Steak\",\"description\":\"Tuna steak with garlic butter and asparagus.\",\"servings\":1,\"prep\":20,\"reminders\":[{\"data\":\"Do not overcook the tuna.\"}],\"ingredients\":[{\"name\":\"Tuna Steak\",\"description\":\"Rich in omega-3 and protein.\",\"quantity\":200,\"units\":\"grams\",\"calories\":280,\"macros\":{\"proteins\":50.0,\"carbs\":0.0,\"fats\":10.0},\"allergens\":[\"Fish\"]},{\"name\":\"Asparagus\",\"description\":\"Nutritious green vegetable.\",\"quantity\":100,\"units\":\"grams\",\"calories\":20,\"macros\":{\"proteins\":2.2,\"carbs\":3.7,\"fats\":0.2},\"allergens\":[]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-29T19:00\",\"recipe\":{\"name\":\"Chicken Curry\",\"description\":\"Spicy chicken curry with coconut milk.\",\"servings\":4,\"prep\":45,\"reminders\":[{\"data\":\"Simmer for at least 20 minutes for depth of flavor.\"}],\"ingredients\":[{\"name\":\"Chicken Thighs\",\"description\":\"Flavorful and juicy cuts.\",\"quantity\":500,\"units\":\"grams\",\"calories\":1090,\"macros\":{\"proteins\":90.0,\"carbs\":0.0,\"fats\":80.0},\"allergens\":[]},{\"name\":\"Coconut Milk\",\"description\":\"Rich and creamy base.\",\"quantity\":200,\"units\":\"milliliters\",\"calories\":360,\"macros\":{\"proteins\":4.0,\"carbs\":8.0,\"fats\":36.0},\"allergens\":[]}]}}," +
                // Day 6
                "{\"type\":\"Breakfast\",\"date\":\"2024-11-30T08:00\",\"recipe\":{\"name\":\"Avocado Toast\",\"description\":\"Creamy avocado spread over whole-grain toast.\",\"servings\":1,\"prep\":10,\"reminders\":[{\"data\":\"Toast the bread until golden brown.\"}],\"ingredients\":[{\"name\":\"Whole-Grain Bread\",\"description\":\"Base for the toast.\",\"quantity\":1,\"units\":\"slice\",\"calories\":110,\"macros\":{\"proteins\":4.0,\"carbs\":20.0,\"fats\":1.5},\"allergens\":[\"Gluten\"]},{\"name\":\"Avocado\",\"description\":\"Rich in healthy fats.\",\"quantity\":50,\"units\":\"grams\",\"calories\":80,\"macros\":{\"proteins\":1.0,\"carbs\":4.0,\"fats\":7.0},\"allergens\":[]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-11-30T12:30\",\"recipe\":{\"name\":\"Turkey Sandwich\",\"description\":\"Classic sandwich with lean turkey and fresh veggies.\",\"servings\":1,\"prep\":10,\"reminders\":[{\"data\":\"Spread mustard or mayonnaise for extra flavor.\"}],\"ingredients\":[{\"name\":\"Whole-Grain Bread\",\"description\":\"Fiber-rich base.\",\"quantity\":2,\"units\":\"slices\",\"calories\":220,\"macros\":{\"proteins\":8.0,\"carbs\":40.0,\"fats\":3.0},\"allergens\":[\"Gluten\"]},{\"name\":\"Turkey Breast\",\"description\":\"Lean protein filling.\",\"quantity\":100,\"units\":\"grams\",\"calories\":120,\"macros\":{\"proteins\":24.0,\"carbs\":0.0,\"fats\":1.0},\"allergens\":[]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-11-30T19:00\",\"recipe\":{\"name\":\"Salmon with Broccoli\",\"description\":\"Grilled salmon with roasted broccoli and lemon zest.\",\"servings\":1,\"prep\":30,\"reminders\":[{\"data\":\"Season the salmon with herbs and spices.\"}],\"ingredients\":[{\"name\":\"Salmon\",\"description\":\"Rich in omega-3 and protein.\",\"quantity\":200,\"units\":\"grams\",\"calories\":360,\"macros\":{\"proteins\":40.0,\"carbs\":0.0,\"fats\":20.0},\"allergens\":[\"Fish\"]},{\"name\":\"Broccoli\",\"description\":\"Nutrient-dense vegetable.\",\"quantity\":150,\"units\":\"grams\",\"calories\":45,\"macros\":{\"proteins\":3.8,\"carbs\":8.0,\"fats\":0.5},\"allergens\":[]}]}}," +
                // Day 7
                "{\"type\":\"Breakfast\",\"date\":\"2024-12-01T08:00\",\"recipe\":{\"name\":\"Smoothie Bowl\",\"description\":\"Blended fruit topped with granola and nuts.\",\"servings\":1,\"prep\":10,\"reminders\":[{\"data\":\"Use frozen fruits for a creamier texture.\"}],\"ingredients\":[{\"name\":\"Banana\",\"description\":\"Sweet and creamy base.\",\"quantity\":100,\"units\":\"grams\",\"calories\":89,\"macros\":{\"proteins\":1.1,\"carbs\":23.0,\"fats\":0.3},\"allergens\":[]},{\"name\":\"Almond Milk\",\"description\":\"Low-calorie liquid base.\",\"quantity\":200,\"units\":\"milliliters\",\"calories\":30,\"macros\":{\"proteins\":1.0,\"carbs\":1.0,\"fats\":2.5},\"allergens\":[\"Nuts\"]}]}}, " +
                "{\"type\":\"Lunch\",\"date\":\"2024-12-01T12:30\",\"recipe\":{\"name\":\"Pasta Salad\",\"description\":\"Cold pasta with cherry tomatoes and feta cheese.\",\"servings\":2,\"prep\":20,\"reminders\":[{\"data\":\"Chill the salad before serving.\"}],\"ingredients\":[{\"name\":\"Pasta\",\"description\":\"Base ingredient for the salad.\",\"quantity\":100,\"units\":\"grams\",\"calories\":350,\"macros\":{\"proteins\":10.0,\"carbs\":70.0,\"fats\":1.5},\"allergens\":[\"Gluten\"]},{\"name\":\"Feta Cheese\",\"description\":\"Tangy and salty topping.\",\"quantity\":50,\"units\":\"grams\",\"calories\":75,\"macros\":{\"proteins\":4.0,\"carbs\":1.0,\"fats\":6.0},\"allergens\":[\"Dairy\"]}]}}, " +
                "{\"type\":\"Dinner\",\"date\":\"2024-12-01T19:00\",\"recipe\":{\"name\":\"Stuffed Bell Peppers\",\"description\":\"Bell peppers filled with quinoa, beans, and cheese.\",\"servings\":2,\"prep\":40,\"reminders\":[{\"data\":\"Bake at 375°F for 30 minutes.\"}],\"ingredients\":[{\"name\":\"Bell Peppers\",\"description\":\"Edible containers for stuffing.\",\"quantity\":2,\"units\":\"units\",\"calories\":50,\"macros\":{\"proteins\":1.0,\"carbs\":10.0,\"fats\":0.5},\"allergens\":[]},{\"name\":\"Quinoa\",\"description\":\"Protein-rich stuffing.\",\"quantity\":100,\"units\":\"grams\",\"calories\":120,\"macros\":{\"proteins\":4.0,\"carbs\":21.0,\"fats\":1.9},\"allergens\":[]}]}}]}";
    }

}

